---
language: node_js
node_js:
  - "9"
services:
  - mongodb
  - postgresql
env:
  - PGUSER=postgres PGDATABASE=machinomy_test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add lerna
  - yarn global add codecov
  - lerna bootstrap
before_script:
  - psql -c 'create database machinomy_test;' -U postgres -d postgres
script:
  - yarn run lint
  - yarn run build
  - cd packages/machinomy && yarn migrate && cd ../
  - yarn run test
  - yarn run coverage
after_script:
  - ls packages/contracts
  - bash <(curl -s https://codecov.io/bash) -s packages/contracts -t $CODECOV
